// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace projetoinoa.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230130224041_AdicionandoAtributoFaltantesDoMonitoramento")]
    partial class AdicionandoAtributoFaltantesDoMonitoramento
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.2");

            modelBuilder.Entity("MvcMoeda.Models.Moeda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Moeda");
                });

            modelBuilder.Entity("MvcMonitoramento.Models.Monitoramento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MoedaId1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MoedaId2")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("ValorDeCompra")
                        .HasColumnType("REAL");

                    b.Property<float>("ValorDeVenda")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("MoedaId1");

                    b.HasIndex("MoedaId2");

                    b.ToTable("Monitoramento");
                });

            modelBuilder.Entity("MvcMonitoramento.Models.Monitoramento", b =>
                {
                    b.HasOne("MvcMoeda.Models.Moeda", "Moeda1")
                        .WithMany()
                        .HasForeignKey("MoedaId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MvcMoeda.Models.Moeda", "Moeda2")
                        .WithMany()
                        .HasForeignKey("MoedaId2")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Moeda1");

                    b.Navigation("Moeda2");
                });
#pragma warning restore 612, 618
        }
    }
}
